name: appsatb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.2
  pedometer: ^1.2.0
  video_player: ^0.10.11+1
  chewie: ^0.9.10
  percent_indicator: ^2.1.4
  flutter_svg: ^0.17.4
  shared_preferences: ^0.5.7+3
  uuid: ^2.0.4
  sqflite: ^1.3.1
  path_provider: ^1.5.10
  font_awesome_flutter: ^8.8.1
  charts_flutter: ^0.9.0
  intl: ^0.16.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - images/atblogo.png
    - images/weight_arrow.svg
    - images/person.svg
    - images/pacman.svg
    - images/circle.svg
    - images/bmi.jpg
    - images/Sedia.gif
    - images/Tahniah.png
    - images/senamrobik.gif
    - images/OtotPerutPemula.png
    - images/OtotPerutMenengah.png
    - images/OtotPerutLanjutan.png
    - images/LenganPemula.png
    - images/LenganMenengah.png
    - images/LenganLanjutan.png
    - images/DadaPemula.png
    - images/DadaMenengah.png
    - images/DadaLanjutan.png
    - images/KakiPemula.png
    - images/KakiMenengah.png
    - images/KakiLanjutan.png
    - images/BahuDanPemula.png
    - images/BahuDanMenengah.png
    - images/BahuDanLanjutan.png
    - images/3088.jpg
    - images/PendakiGunung.gif
    - images/CrunchPerut.gif
    - images/LompatBintang.gif
    - images/CurlBarbelKakiKiri.gif
    - images/CurlBarbelKakiKanan.gif
    - images/PutarRusia.gif
    - images/Plank.gif
    - images/AngkatKaki.gif
    - images/SentuhTumit.gif
    - images/PereganganKobra.gif
    - images/ppbkiri.gif
    - images/ppbkanan.gif
    - images/AngkatTangan.gif
    - images/AngkatLengan.gif
    - images/TricipDip.gif
    - images/PutarLenganJam.gif
    - images/PutarLenganLawanJam.gif
    - images/PushUpBerlian.gif
    - images/TekanLenganDada.gif
    - images/CurlBarbelKakiKiri.gif
    - images/CurlBarbelKakiKanan.gif
    - images/PlankDiagonal.gif
    - images/Meninju.gif
    - images/PushUp.gif
    - images/Inchworms.gif
    - images/PushUpDinding.gif
    - images/PereganganTrisepKiri.gif
    - images/PereganganTrisepKanan.gif
    - images/PereganganBisepBerdiriKiri.gif
    - images/PereganganBisepKanan.gif
    - images/PushUpDiatasBangku.gif
    - images/PushUpLutut.gif
    - images/PushUpTanganMelebar.gif
    - images/PushUpDitekuk.gif
    - images/PushUpHindu.gif
    - images/PereganganDada.gif
    - images/LompatSamping.gif
    - images/Squat.gif
    - images/AngkatKakiBaringKanan.gif
    - images/AngkatKakiBaringKiri.gif
    - images/TerjangMundur.gif
    - images/TendangKeldaiKanan.gif
    - images/TendangKeldaiKiri.gif
    - images/PereganganKuadrisepKiri.gif
    - images/PereganganKuadrisepKanan.gif
    - images/PereganganLututKeDadaKiri.gif
    - images/PereganganLututKeDadaKanan.gif
    - images/AngkatBetisMenghadapTembok.gif
    - images/PereganganBetisKiri.gif
    - images/PereganganBetisKanan.gif
    - images/PereganganLantaiKiri.gif
    - images/PereganganLantaiKanan.gif
    - images/TarikanRomboid.gif
    - images/JongkokSumo.gif
    - images/GuntingLengan.gif
    - images/SikapKucing.gif
    - images/PushUpTrisepTelungkup.gif
    - images/RemasanRomboid.gif
    - images/SikapAnak.gif
    - images/Ekstensi.gif
    - images/AngkatTrisepDilantai.gif
    - images/EngselPinggul.gif
    - images/PushUpMelayang.gif
    - images/Superman.gif
    - images/SitUpSilang.gif
    - images/PapanMenyampingKiri.gif
    - images/PapanMenyampingKanan.gif
    - images/JambatanBokong.gif
    - images/CrunchSepeda.gif
    - images/SitUpV.gif
    - images/PushUpDanPusingan.gif
    - images/KananPlankSisi.gif
    - images/KiriPlankSisi.gif
    - images/PushUpLenganDiagonal.gif
    - images/PereganganBahu.gif
    - images/Burpee.gif
    - images/LompatTanpaTali.gif
    - images/PushUpMiliter.gif
    - images/HookUp.gif
    - images/FireHydrantKanan.gif
    - images/FireHydrantKiri.gif
    - images/Lunge.gif
    - images/SisiLingkaranKiri.gif
    - images/SisiLingkaranKanan.gif
    - images/JongkokSumo2.gif
    - images/TendangRinganBalik.gif
    - images/DudukDiDinding.gif
    - images/AngkatBetisTerentang.gif
    - images/LompatBetisKiri.gif
    - images/LompatBetisKanan.gif
    - images/SitUp.gif
    - images/LingkaranLengan.gif
    - images/PushUpSpiderman.gif
    - images/PushUpKBangku.gif
    - images/Hiper.gif
    - images/PushUpTombak.gif
    - images/MPushUp.gif
    - images/PushUpTelentang.gif
    - images/AngkatY.gif
    - images/Angel.gif
    - images/Gator.gif
    - images/CrunchCurlKiri.gif
    - images/CrunchCurlKanan.gif
    - images/Pintukiri.gif
    - images/PintuKanan.gif
    - images/PushUpTRM.gif
    - images/AngkatBawahKiri.gif
    - images/AngkatBawahKanan.gif
    - images/Bungkuk.gif
    - images/LJongkok.gif
    - images/KiriTendang.gif
    - images/KananTendang.gif
    - images/KupuKupu.gif
    - images/TanduSandar.gif
    - images/TahanTembokKiri.gif
    - images/TahanTembokKanan.gif
    - images/Cal.jpg
    - images/Sarapan.jpg
    - images/MT.jpg
    - images/MM.jpg
    - images/RotiCanai.jpg
    - images/NasiGoreng.jpg
    - images/NasiDagang.jpg
    - images/Lontong.jpg
    - images/Nasi.jpg
    - images/AyamG.jpg
    - images/AyamKari.jpg
    - images/Sayur.jpg
    - images/IkanBakar.jpg
    - images/Ikan3rasa.jpg
    - images/SawiG.jpg
    - images/Kailan.jpg
    - images/map.png
    - images/burn.png
    - images/step.png
    - images/senamrobik.3gp


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
